apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: dev
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flux-ui
  namespace: dev
spec:
  interval: 1m0s
  url: https://raw.githubusercontent.com/sureshamk/flux-ui/master/flux-ui