apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: dev
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ccowley
  namespace: dev
spec:
  interval: 1m0s
  url: https://helm.cowley.tech