apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo


---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apache
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/apache
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: dev


---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-ui
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize/flux-ui
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: dev

